### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by BlesslinJerishR**
- Page titles - no issues found 
- Image text alternatives - Add alt attributes : [Changed alt attributes](https://github.com/BlesslinJerishR/Microfolio/pull/7/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R18-R359)
- Text headings - no issues found
- Color contrast - no issues found
- Resize - no issues found
- Interaction - Add tab buttons
- Moving content - no issues found
- Multimedia - Add Background Images
- The basic structure of the page - no issues found

### CODE REVIEW

**Review by LionRouge1 — CHANGES_REQUESTED** [review]
Hi @BlesslinJerishR, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost

## Highlights
- Good job writing a clear and understandable report :+1: 
- Nice work including the evaluation of all necessary accessibility of your web page :1st_place_medal: 

## Required Changes ♻️
- [x] Kindly add the link to the corresponding line of code in your pull request where you made changes to the accessibility issue that you found as requested in the project requirement.
Screenshot from 2023-04-04 11-18-43

[Read about how to link to a line of code in your pull request](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148).

- [x] Nice work detecting some issues about the **Image text alternatives** :clap: However I still noticed some `img` tags without `alt` attribute. Please make sure every image has `alt` with an appropriate alternative text, it is used by people who do not see the image and use screen readers to hear the `alt` text read out. 
_**HIT:**  Use this [website](https://validator.w3.org/) to check about **Image text alternatives**_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
[OPTIONAL]
- [x] I also noticed some **text headings** issues (Hierarchy is not meaningful, skipped some levels). Kindly read this [section](https://www.w3.org/WAI/test-evaluate/preliminary/#headings) to learn more about **Headings Hierarchy**.
_**HIT:**  Use this [website](https://validator.w3.org/) to check about **text headings** and make sure that you selected the **Show Outline** checkbox before clicking the button **Check**._ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BlesslinJerishR** [comment]
Hi @LionRouge1 , Regarding the linking of lines to the alt attribute every line can be founded in the file changed commit section. What line exactly do I need to link sir?

**Comment by BlesslinJerishR** [comment]
These are the alt attributes we changed, Thank you.

- Image text alternatives - Add alt attributes : [Changed alt attributes](https://github.com/BlesslinJerishR/Microfolio/pull/7/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R18-R359)

**Comment by LionRouge1** [comment]
@BlesslinJerishR, You are most welcome:hugs: 
Kindly submit the PR for re-review in your dashboard

**Comment by BlesslinJerishR** [comment]
> @BlesslinJerishR, You are most welcome. Kindly submit the PR for re-review in your dashboard

Yes sir , I have re applied for review in my dashboard @LionRouge1 .

**Review by jerryowusu — APPROVED** [review]
Hi @BlesslinJerishR and @shihabrafio, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

CookedDelectableDolphin-size_restricted


## Highlights
Good job for making the requested changes. :heavy_check_mark: 
Nice Pull request summary :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
